name: Deploy wallaby
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        run: chmod +x setup.sh && sh setup.sh
        env:
          ACCOUNT_TYPE: ${{secrets.ACCOUNT_TYPE}}
          API_TOKEN: ${{secrets.API_KEY}}
          AUTH_PROVIDER: ${{secrets.AUTH_PROVIDER}}
          AUTH_URI: ${{secrets.AUTH_URI}}
          CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_URL: ${{secrets.CLIENT_URL}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          SHEET_KEY: ${{secrets.SHEET_KEY}}
          TOKEN_URI: ${{secrets.TOKEN_URI}}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add path
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install packages
        run: poetry install --no-interaction
      - name: Run test
        run: poetry run python -m pytest
